import { Link } from "@tanstack/react-router";
import { Apple, ArrowRight, Check, Droplets, Eye, GlassWater, Heart, Leaf, Lightbulb, RefreshCw, Sparkles, Users, Utensils, X } from "lucide-react";
import { useState, type ComponentType } from "react";
import type { LucideProps } from "lucide-react";
import heroImage from "../assets/hero-family-healthy.jpg";
import waterImage from "../assets/hydration-child.jpg";
import cookingImage from "../assets/kids-cooking.jpg";
import { Button } from "./ui/button";
import { Progress } from "./ui/progress";

export const meta = (title: string, description: string) => ({ meta: [{ title: `${title} | NutriKIDS` }, { name: "description", content: description }, { property: "og:title", content: `${title} | NutriKIDS` }, { property: "og:description", content: description }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] });
const PageHero = ({ eyebrow, title, text }: { eyebrow: string; title: string; text: string }) => <section className="relative overflow-hidden bg-secondary/45"><div className="absolute -right-20 top-8 size-56 rounded-full border-[28px] border-primary/8 animate-drift"/><div className="absolute right-[28%] top-10 size-8 rounded-[65%_35%_60%_40%] bg-primary/15 animate-float-soft"/><div className="relative mx-auto max-w-7xl px-5 py-18 lg:px-8 lg:py-24"><p className="mb-3 text-sm font-bold uppercase text-primary">{eyebrow}</p><h1 className="max-w-3xl text-4xl font-bold leading-tight text-forest md:text-6xl">{title}</h1><p className="mt-5 max-w-2xl text-lg leading-relaxed text-muted-foreground">{text}</p></div></section>;
const TipStrip = ({ children }: { children: React.ReactNode }) => <div className="border-l-4 border-sun bg-accent/45 p-5 text-foreground"><Lightbulb className="mb-2 text-primary" aria-hidden="true" /><p className="font-medium leading-relaxed">{children}</p></div>;
type PagePath = "/" | "/alimentacao-saudavel" | "/agua" | "/o-que-fazer" | "/o-que-evitar" | "/dicas" | "/quiz";
const NextPage = ({ to, eyebrow, title, text }: { to: PagePath; eyebrow: string; title: string; text: string }) => <section className="next-page-band"><div className="absolute -right-10 -top-12 size-44 rounded-full border-[24px] border-primary-foreground/10 animate-drift"/><div className="absolute bottom-6 left-[8%] size-8 rounded-[70%_30%_65%_35%] bg-sun animate-float-soft"/><div className="relative mx-auto grid max-w-7xl items-center gap-7 px-5 py-12 md:grid-cols-[1fr_auto] lg:px-8"><div><p className="text-xs font-bold uppercase text-secondary">{eyebrow}</p><h2 className="mt-2 text-3xl text-primary-foreground md:text-4xl">{title}</h2><p className="mt-3 max-w-2xl text-primary-foreground/75">{text}</p></div><Button asChild size="xl" variant="cream" className="group rounded-2xl px-7"><Link to={to}>Continuar jornada <ArrowRight className="transition-transform group-hover:translate-x-1"/></Link></Button></div></section>;

export function HomePage() { return <>
  <section className="relative overflow-hidden bg-forest text-primary-foreground"><div className="absolute -left-24 top-32 size-56 rounded-full border-[34px] border-primary-foreground/8 animate-drift"/><div className="mx-auto grid min-h-[680px] max-w-7xl items-center gap-10 px-5 py-16 lg:grid-cols-[.88fr_1.12fr] lg:px-8"><div className="z-10 animate-reveal"><p className="mb-4 text-sm font-bold uppercase text-secondary">NutriKIDS • Alimentação na infância</p><h1 className="text-5xl font-bold leading-[1.02] md:text-7xl">Pequenas escolhas,<br/><span className="text-secondary">grandes hábitos.</span></h1><p className="mt-6 max-w-xl text-lg leading-relaxed opacity-85">Descubra formas simples de incentivar uma alimentação mais saudável para as crianças no dia a dia.</p><div className="mt-8 flex flex-wrap gap-3"><Button asChild size="xl" variant="cream" className="rounded-2xl"><Link to="/alimentacao-saudavel">Começar a aprender <ArrowRight /></Link></Button><Button asChild size="xl" variant="coral" className="rounded-2xl"><Link to="/quiz">Fazer o quiz</Link></Button></div><div className="mt-10 flex flex-wrap gap-x-7 gap-y-3 text-sm text-primary-foreground/75"><span className="flex items-center gap-2"><Leaf className="size-4 text-secondary"/> Ideias práticas</span><span className="flex items-center gap-2"><Heart className="size-4 text-secondary"/> Sem pressão</span><span className="flex items-center gap-2"><Sparkles className="size-4 text-secondary"/> Aprendizado leve</span></div></div><div className="relative lg:translate-x-10"><div className="overflow-hidden rounded-[4rem_1.5rem_5rem_2rem] border-8 border-primary-foreground/10"><img src={heroImage} alt="Família preparando uma refeição colorida e equilibrada em casa" width={1536} height={1152} className="aspect-[4/3] w-full object-cover transition-transform duration-700 hover:scale-[1.03]" /></div><Apple className="absolute -left-4 -top-6 size-12 animate-drift text-secondary" aria-hidden="true"/><Droplets className="absolute -bottom-5 right-8 size-12 animate-float-soft text-primary-foreground/70" aria-hidden="true"/></div></div></section>
  <section className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><div className="grid gap-10 lg:grid-cols-[.7fr_1.3fr]"><div className="reveal-on-scroll"><p className="text-sm font-bold uppercase text-primary">Uma jornada possível</p><h2 className="mt-2 text-3xl font-bold text-forest md:text-4xl">Hábitos crescem um passo de cada vez</h2><p className="mt-4 text-muted-foreground">Não é preciso transformar tudo de uma vez. Comece observando, convide para experimentar e repita o que funciona.</p></div><div className="grid gap-4 md:grid-cols-3">{[["01","Entender","Observe a rotina e reconheça pequenas oportunidades."],["02","Experimentar","Convide a criança a conhecer cores, cheiros e sabores."],["03","Criar hábitos","Repita atitudes possíveis com calma e consistência."]].map(([n,t,d],i)=><article key={t} className={`journey-step reveal-on-scroll ${i===1?"md:translate-y-7":""}`}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></div></section>
  <section className="bg-muted"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-20 lg:grid-cols-[1.1fr_.9fr] lg:px-8"><div className="relative overflow-hidden rounded-[1.25rem_3.5rem_1.25rem_3.5rem]"><img src={cookingImage} alt="Crianças participando do preparo de alimentos frescos" width={1200} height={912} loading="lazy" className="aspect-[5/4] h-full w-full object-cover transition-transform duration-700 hover:scale-[1.03]"/><div className="absolute bottom-0 left-0 max-w-xs bg-forest/95 p-5 text-primary-foreground"><p className="text-sm font-bold text-secondary">Participar também ensina</p><p className="mt-1 text-sm opacity-80">Lavar, escolher e organizar são pequenas formas de conhecer os alimentos.</p></div></div><div className="self-center"><h2 className="text-3xl text-forest">Cinco ideias para levar com você</h2><div className="mt-7 divide-y divide-border">{["Variedade torna o prato mais interessante","Frutas e verduras podem aparecer de muitos jeitos","Água visível fica mais fácil de lembrar","Rotina traz previsibilidade às refeições","Participar aproxima a criança dos alimentos"].map((x,i)=><div key={x} className="flex items-center gap-4 py-4"><span className="grid size-9 shrink-0 place-items-center rounded-full bg-secondary font-display font-bold text-primary">{i+1}</span><p className="font-medium">{x}</p></div>)}</div><div className="mt-8"><TipStrip>Seu filho recusou um alimento novo? Conhecer um sabor pode levar tempo. Ofereça novamente em outro dia, sem pressão.</TipStrip></div></div></div></section>
  <NextPage to="/alimentacao-saudavel" eyebrow="Próxima descoberta" title="Como montar uma alimentação variada?" text="Explore um prato interativo e descubra como diferentes grupos podem aparecer na rotina."/>
</> }

export function HealthyPage() { const [part,setPart]=useState("verduras"); const info: Record<string,string>={verduras:"Cores, texturas e preparos diferentes ampliam as experiências.",graos:"Arroz, milho, aveia e outros grãos fazem parte de refeições variadas.",feijoes:"Feijões e outras leguminosas combinam com diferentes refeições.",proteinas:"Ovos, carnes e outras opções podem compor o prato da família."}; return <><PageHero eyebrow="Alimentação saudável" title="Variedade no prato, curiosidade à mesa" text="Uma alimentação variada não precisa ser perfeita. Ela pode ser construída com alimentos diferentes, preparos possíveis e respeito ao ritmo da criança."/><section className="mx-auto grid max-w-7xl gap-14 px-5 py-20 lg:grid-cols-2 lg:px-8"><div><h2 className="text-3xl text-forest">Explore um prato variado</h2><p className="mt-3 text-muted-foreground">Selecione uma parte para descobrir seu papel na variedade — sem regras rígidas ou dieta prescrita.</p><div className="relative mx-auto mt-10 aspect-square max-w-md rounded-full border-[12px] border-cream bg-card shadow-sm"><button aria-label="Verduras e legumes" onClick={()=>setPart("verduras")} className="absolute left-[8%] top-[8%] h-[42%] w-[84%] rounded-t-full bg-leaf text-primary-foreground transition-transform hover:scale-[1.02] focus:outline-none focus:ring-4 focus:ring-ring"><Leaf className="mx-auto size-10"/><span className="font-semibold">Verduras e legumes</span></button><button onClick={()=>setPart("graos")} className="absolute bottom-[8%] left-[8%] h-[40%] w-[40%] rounded-bl-full bg-sun text-forest transition-transform hover:scale-[1.02]"><span className="font-semibold">Grãos</span></button><button onClick={()=>setPart("feijoes")} className="absolute bottom-[8%] left-[50%] h-[40%] w-[20%] bg-coral text-coral-foreground transition-transform hover:scale-[1.02]"><span className="text-sm font-semibold">Feijões</span></button><button onClick={()=>setPart("proteinas")} className="absolute bottom-[8%] right-[8%] h-[40%] w-[20%] rounded-br-full bg-water text-forest transition-transform hover:scale-[1.02]"><span className="text-sm font-semibold">Outros</span></button></div></div><div className="self-center"><p className="text-sm font-bold uppercase text-coral">No prato</p><h3 className="mt-2 text-3xl capitalize text-forest">{part}</h3><p className="mt-4 text-lg leading-relaxed">{info[part]}</p><div className="mt-10"><TipStrip>Um prato colorido não precisa ter todas as cores todos os dias. A variedade acontece ao longo da rotina.</TipStrip></div></div></section><DidYouKnow/><NextPage to="/agua" eyebrow="Próxima descoberta" title="Água por perto, cuidado presente" text="Veja maneiras simples de tornar a água mais disponível ao longo do dia."/></> }

function DidYouKnow(){return <section className="bg-forest text-primary-foreground"><div className="mx-auto max-w-7xl px-5 py-16 lg:px-8"><p className="text-sm font-bold uppercase text-sun">Você sabia?</p><div className="mt-6 grid gap-8 md:grid-cols-3"><p>Cheirar, tocar e ajudar no preparo também são formas de conhecer um alimento.</p><p>O mesmo alimento pode parecer diferente quando muda o corte ou o preparo.</p><p>Comer junto permite que a criança observe os hábitos dos adultos.</p></div></div></section>}

export function WaterPage(){return <><PageHero eyebrow="Água e hidratação" title="Água por perto, cuidado presente" text="A água participa de muitas funções do corpo. No dia a dia, o mais útil é facilitar o acesso e lembrar com naturalidade."/><section className="mx-auto grid max-w-7xl gap-12 px-5 py-20 lg:grid-cols-2 lg:px-8"><img src={waterImage} alt="Criança pegando sua garrafa de água após brincar" width={1200} height={912} loading="lazy" className="aspect-[4/3] w-full rounded-[2rem_4rem_2rem_2rem] object-cover"/><div className="self-center"><h2 className="text-3xl text-forest">Como incentivar sem complicar</h2><div className="mt-7 space-y-6">{[["Deixe visível","Mantenha uma garrafinha ou copo em um lugar fácil de alcançar."],["Leve nos passeios","Inclua a água entre os itens da mochila."],["Dê o exemplo","Beba água perto da criança ao longo do dia."],["Crie lembretes naturais","Ofereça água após brincadeiras e junto das refeições."]].map(([t,d])=><div key={t} className="flex gap-4"><GlassWater className="mt-1 shrink-0 text-water"/><div><h3 className="font-sans text-lg font-bold">{t}</h3><p className="text-muted-foreground">{d}</p></div></div>)}</div></div></section><section className="bg-water/15"><div className="mx-auto max-w-4xl px-5 py-14 text-center"><Droplets className="mx-auto size-10 text-water"/><h2 className="mt-3 text-2xl text-forest">Cada criança tem necessidades diferentes</h2><p className="mt-3 text-muted-foreground">Idade, clima, atividades e alimentação fazem diferença. Por isso, não existe uma quantidade universal que sirva para todas.</p></div></section><NextPage to="/o-que-fazer" eyebrow="Próxima descoberta" title="Atitudes que cabem na vida real" text="Conheça ações acolhedoras para construir uma rotina mais tranquila em família."/></>}

export function DoPage(){const items: Array<{Icon: ComponentType<LucideProps>; title:string; description:string}>=[{Icon:Users,title:"Faça refeições em família",description:"A presença e o exemplo ajudam a construir uma rotina tranquila."},{Icon:Apple,title:"Ofereça variedade",description:"Alterne cores, texturas e formas de preparo ao longo dos dias."},{Icon:Eye,title:"Deixe opções acessíveis",description:"Frutas lavadas e água visível facilitam escolhas cotidianas."},{Icon:Utensils,title:"Envolva a criança",description:"Ela pode lavar folhas, escolher uma fruta ou organizar a mesa."},{Icon:RefreshCw,title:"Apresente novamente",description:"Uma recusa hoje não precisa ser a resposta para sempre."},{Icon:Heart,title:"Acolha o ritmo",description:"Convide para experimentar, sem forçar ou negociar cada garfada."}];return <><PageHero eyebrow="O que fazer" title="Atitudes que cabem na vida real" text="Os responsáveis organizam o ambiente e oferecem possibilidades. A criança participa, experimenta e aprende no próprio ritmo."/><section className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><div className="grid gap-x-12 gap-y-0 md:grid-cols-2">{items.map(({Icon,title,description},i)=><article key={title} className={`flex gap-5 border-b border-border py-7 ${i%2?"md:translate-y-8":""}`}><span className="grid size-12 shrink-0 place-items-center rounded-full bg-secondary text-primary"><Icon/></span><div><h2 className="font-sans text-xl font-bold text-forest">{title}</h2><p className="mt-2 text-muted-foreground">{description}</p></div></article>)}</div></section><section className="mx-auto grid max-w-7xl gap-10 px-5 pb-20 lg:grid-cols-[1.1fr_.9fr] lg:px-8"><img src={cookingImage} alt="Responsável e crianças lavando verduras e organizando frutas" width={1200} height={912} loading="lazy" className="rounded-[3rem_1rem_3rem_1rem]"/><div className="self-center"><p className="text-sm font-bold uppercase text-coral">Experimente hoje</p><h2 className="mt-2 text-3xl text-forest">Convide para uma pequena missão</h2><p className="mt-4 text-lg text-muted-foreground">Peça à criança para escolher duas cores de alimentos para a próxima refeição. Participar pode despertar interesse sem transformar o momento em obrigação.</p></div></section><NextPage to="/o-que-evitar" eyebrow="Próxima descoberta" title="Menos pressão, mais confiança" text="Veja atitudes que podem ser substituídas por conversas mais leves e respeitosas."/></>}

export function AvoidPage(){const items=[["Pressionar para comer","A pressão pode deixar a refeição tensa. Ofereça, acompanhe e respeite sinais de fome e saciedade."],["Usar comida como recompensa","Quando a sobremesa vira prêmio, outros alimentos podem parecer apenas uma tarefa."],["Chamar alimentos de proibidos","Regras rígidas podem aumentar a curiosidade e a culpa. Prefira conversar sobre frequência e contexto."],["Criar medo ou culpa","Frases assustadoras não ensinam equilíbrio. Fale de cuidado com linguagem simples e neutra."]];return <><PageHero eyebrow="O que evitar" title="Menos pressão, mais confiança" text="Nenhuma família acerta sempre. Observar a forma como falamos sobre comida já é um bom começo — sem culpa e sem julgamento."/><section className="mx-auto max-w-5xl px-5 py-20"><div className="space-y-4">{items.map(([t,d],i)=><article key={t} className="grid gap-4 border-b border-border py-7 md:grid-cols-[70px_1fr_1.4fr]"><span className="font-display text-3xl text-coral">0{i+1}</span><h2 className="font-sans text-xl font-bold text-forest">{t}</h2><p className="text-muted-foreground">{d}</p></article>)}</div><div className="mt-14 bg-secondary/50 p-8"><h2 className="text-2xl text-forest">Troque “só mais uma colher” por uma pergunta</h2><p className="mt-3">“Como seu corpo está se sentindo: ainda com fome ou já satisfeito?” Assim, a criança começa a perceber os próprios sinais.</p></div></section><NextPage to="/dicas" eyebrow="Próxima descoberta" title="Ideias simples para experimentar hoje" text="Encontre sugestões práticas para frutas, água, rotina e participação da criança."/></>}

export function TipsPage(){const tips=[["Deixe as frutas fáceis de encontrar","Quando uma opção saudável está disponível e visível, fica mais fácil incorporá-la à rotina.","Deixe algumas frutas lavadas e acessíveis."],["Dê duas opções possíveis","Escolhas simples aumentam a participação sem deixar toda a decisão para a criança.","Pergunte: você prefere banana ou mamão?"],["Aproxime sem exigir","O contato tranquilo permite conhecer um alimento sem transformar a prova em disputa.","Coloque uma pequena porção nova ao lado de algo conhecido."],["Organize uma rotina possível","Horários aproximados ajudam a criança a saber quando haverá outra refeição.","Escolha um momento do dia para a família comer junta."],["Convide para preparar","Mexer, lavar e montar aproxima a criança dos ingredientes.","Convide-a para lavar uma fruta ou separar folhas."],["Mantenha água à vista","Lembretes visuais tornam o hábito mais natural durante o dia.","Encha uma garrafinha e deixe em um local acessível."]];return <><PageHero eyebrow="Dicas para o dia a dia" title="Pequenas ações para experimentar hoje" text="Escolha uma ideia que faça sentido para sua casa. Não é preciso mudar tudo de uma vez."/><section className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><div className="grid gap-5 md:grid-cols-2">{tips.map(([t,why,today],i)=><article key={t} className={`border border-border bg-card p-7 ${i===0||i===3?"md:col-span-2 md:grid md:grid-cols-3 md:gap-8":""}`}><div><p className="text-xs font-bold uppercase text-coral">Dica {i+1}</p><h2 className="mt-2 font-sans text-xl font-bold text-forest">{t}</h2></div><div className="mt-5 md:mt-0"><p className="text-sm font-bold text-primary">Por que pode ajudar</p><p className="mt-1 text-muted-foreground">{why}</p></div><div className="mt-5 md:mt-0"><p className="text-sm font-bold text-primary">Experimente hoje</p><p className="mt-1">{today}</p></div></article>)}</div></section><NextPage to="/quiz" eyebrow="Última etapa" title="Que tal testar o que você descobriu?" text="Responda a 10 perguntas rápidas e receba explicações ao longo do caminho."/></>}

const questions=[
  ["Quando uma criança recusa um alimento novo, o que pode ajudar?",["Obrigar a terminar","Oferecer novamente, sem pressão","Retirar para sempre"],1,"Conhecer sabores pode levar tempo. Reapresentar com calma é uma boa estratégia."],
  ["Qual atitude aproxima a criança das verduras?",["Participar do preparo","Esconder todos os vegetais","Usar como castigo"],0,"Lavar, escolher e preparar são formas de conhecer os alimentos."],
  ["Como facilitar o consumo de frutas?",["Deixá-las lavadas e acessíveis","Permitir apenas no fim de semana","Oferecer só se pedir"],0,"Opções visíveis e prontas ficam mais fáceis de incluir na rotina."],
  ["Sobre a água, qual ideia faz mais sentido?",["A mesma quantidade serve para todas","Só oferecer quando pedir","Deixar disponível e lembrar naturalmente"],2,"Acesso fácil e lembretes ligados à rotina ajudam, sem impor uma regra universal."],
  ["Uma alimentação variada significa...",["Perfeição em todas as refeições","Diferentes alimentos ao longo da rotina","Comer sempre a mesma salada"],1,"A variedade se constrói ao longo dos dias, não em um prato perfeito."],
  ["Qual hábito traz previsibilidade?",["Horários aproximados para refeições","Comer em qualquer lugar e hora","Pular refeições como punição"],0,"Uma rotina possível ajuda a criança a entender os momentos de comer."],
  ["Como lidar com ultraprocessados?",["Criar medo e culpa","Falar de frequência e contexto","Chamar de alimento proibido"],1,"Conversas neutras sobre frequência ajudam mais que medo ou proibição."],
  ["Na refeição em família, os adultos podem...",["Dar exemplo com tranquilidade","Vigiar cada garfada","Comparar irmãos"],0,"A criança observa comportamentos e aprende também pelo exemplo."],
  ["Pressionar para comer pode...",["Garantir uma boa relação com comida","Deixar a refeição mais tensa","Ensinar a perceber a saciedade"],1,"Pressão pode dificultar a percepção dos sinais do próprio corpo."],
  ["Uma participação adequada para a criança é...",["Escolher todo o cardápio","Lavar uma fruta ou organizar a mesa","Preparar tudo sozinha"],1,"Pequenas tarefas seguras estimulam curiosidade e pertencimento."],
] as const;
export function QuizPage(){
  const [current,setCurrent]=useState(0);
  const [selected,setSelected]=useState<number|null>(null);
  const [score,setScore]=useState(0);
  const [done,setDone]=useState(false);
  const q=questions[current] ?? questions[0];
  const choose=(choice:number)=>{setSelected(choice);if(choice===q[2])setScore(s=>s+1)};
  const next=()=>{if(current===questions.length-1)setDone(true);else{setCurrent(c=>c+1);setSelected(null)}};
  const reset=()=>{setCurrent(0);setSelected(null);setScore(0);setDone(false)};
  if(done){
    const title=score<=4?"Vamos aprender mais!":score<=7?"Você está no caminho!":"Muito bom!";
    return <section className="relative overflow-hidden bg-secondary/35 px-5 py-20 md:py-28">
      <div className="absolute -left-20 top-14 size-52 rounded-full border-[30px] border-primary/10 animate-drift"/>
      <div className="relative mx-auto max-w-2xl rounded-[2.5rem] border border-border bg-card p-8 text-center shadow-[0_24px_70px_oklch(0.25_0.06_150_/_0.12)] md:p-14">
        <span className="mx-auto grid size-20 place-items-center rounded-3xl bg-secondary text-primary animate-soft-pulse"><Sparkles className="size-9"/></span>
        <p className="mt-7 text-sm font-bold uppercase text-primary">Seu resultado: {score} de 10</p>
        <h1 className="mt-2 text-4xl text-forest md:text-5xl">{title}</h1>
        <p className="mx-auto mt-4 max-w-lg text-muted-foreground">O quiz é uma forma de revisar ideias, não uma avaliação da sua família. Cada pequena descoberta conta.</p>
        <Button onClick={reset} size="xl" className="mt-8 rounded-2xl"><RefreshCw/> Refazer o quiz</Button>
      </div>
    </section>
  }
  const answered=selected!==null;
  return <section className="relative overflow-hidden bg-secondary/35 px-4 py-12 md:px-6 md:py-20">
    <div className="absolute -right-24 top-10 size-64 rounded-full border-[38px] border-primary/8 animate-drift"/>
    <div className="absolute -left-10 bottom-28 size-24 rounded-[65%_35%_65%_35%] bg-primary/8 animate-float-soft"/>
    <div className="relative mx-auto max-w-3xl overflow-hidden rounded-[2.5rem] border border-border bg-card shadow-[0_24px_70px_oklch(0.25_0.06_150_/_0.12)]">
      <div className="p-6 pb-3 md:p-9 md:pb-4">
        <div className="mb-6 flex items-center justify-between gap-4">
          <span className="font-display text-2xl font-bold text-forest">Nutri<span className="text-leaf">KIDS</span></span>
          <span className="rounded-full bg-secondary px-4 py-2 text-xs font-bold text-primary">Pergunta {current+1} de 10</span>
        </div>
        <Progress value={((current+1)/questions.length)*100} className="h-3"/>
      </div>
      <div className="px-6 py-7 text-center md:px-10">
        <p className="mb-2 text-xs font-bold uppercase text-primary">Escolha uma resposta</p>
        <h1 className="mx-auto max-w-2xl text-2xl leading-snug text-forest md:text-3xl">{q[0]}</h1>
        <div className="mt-8 grid gap-4 md:grid-cols-2">{q[1].map((option,i)=><button key={option} disabled={answered} onClick={()=>choose(i)} className={`group relative flex min-h-24 items-center gap-4 rounded-2xl border-2 p-4 text-left font-semibold transition-all duration-300 focus:outline-none focus:ring-2 focus:ring-ring disabled:cursor-default ${selected===i?(i===q[2]?"border-primary bg-secondary text-forest":"border-primary/40 bg-muted text-foreground"):"border-border bg-background hover:-translate-y-1 hover:border-primary hover:bg-secondary/45 hover:shadow-lg"}`}><span className="grid size-12 shrink-0 place-items-center rounded-xl bg-secondary text-lg text-primary transition-transform duration-300 group-hover:scale-110">{selected===i?(i===q[2]?<Check/>:<X/>):String.fromCharCode(65+i)}</span>{option}</button>)}</div>
      </div>
      {answered&&<div role="status" className="mx-6 flex gap-4 rounded-2xl border border-primary/20 bg-secondary/55 p-5 animate-reveal md:mx-10"><Sparkles className="shrink-0 text-primary"/><div><p className="font-bold text-forest">{selected===q[2]?"Boa escolha!":"Vale rever esta ideia."}</p><p className="mt-1 text-sm text-muted-foreground">{q[3]}</p></div></div>}
      <div className="flex justify-end p-6 md:p-9">{answered&&<Button size="xl" className="rounded-2xl transition-transform hover:-translate-y-1" onClick={next}>{current===9?"Ver resultado":"Próxima pergunta"}<ArrowRight/></Button>}</div>
    </div>
  </section>
}